import { useEffect, useMemo, useState } from 'react';
import { useNavigate, useSearchParams } from 'react-router-dom';
import { AlertCircle, ArrowDownToLine, ChevronRight, FileJson2, Play, RefreshCw, Search, Shield, Sparkles, Trash2, Workflow } from 'lucide-react';
import { api } from '../lib/api'; import ScoreOrb from '../components/ScoreOrb'; import Toast from '../components/Toast';

export default function Audits(){
 const navigate=useNavigate(); const [params,setParams]=useSearchParams(); const [audits,setAudits]=useState([]); const [selected,setSelected]=useState(null); const [query,setQuery]=useState(''); const [tab,setTab]=useState('findings'); const [busy,setBusy]=useState(false); const [toast,setToast]=useState(null);
 const load=async()=>{try{const data=await api.listAudits();setAudits(data);const id=Number(params.get('id'));const pick=data.find(a=>a.id===id)||data[0]||null;setSelected(pick);if(pick&&!id)setParams({id:String(pick.id)},{replace:true});}catch(e){setToast({type:'error',message:e.message})}};
 useEffect(()=>{load()},[]); useEffect(()=>{const f=()=>document.getElementById('audit-search')?.focus();window.addEventListener('focus-audit-search',f);return()=>window.removeEventListener('focus-audit-search',f)},[]);
 const filtered=useMemo(()=>audits.filter(a=>`${a.project_name} ${a.description}`.toLowerCase().includes(query.toLowerCase())),[audits,query]);
 const choose=(a)=>{setSelected(a);setParams({id:String(a.id)});setTab('findings')};
 const rerun=async()=>{if(!selected)return;setBusy(true);try{const a=await api.startAudit(selected.id);setSelected(a);await load();setToast({message:'Audit rerun completed.'})}catch(e){setToast({type:'error',message:e.message})}finally{setBusy(false)}};
 const remove=async()=>{if(!selected||!confirm(`Delete “${selected.project_name}”?`))return;setBusy(true);try{await api.deleteAudit(selected.id);setParams({});await load();setToast({message:'Audit deleted.'})}catch(e){setToast({type:'error',message:e.message})}finally{setBusy(false)}};
 const download=async()=>{if(!selected)return;try{const report=await api.report(selected.id);const blob=new Blob([JSON.stringify(report,null,2)],{type:'application/json'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download=`audit-${selected.id}-report.json`;a.click();URL.revokeObjectURL(url);setToast({message:'Report downloaded.'})}catch(e){setToast({type:'error',message:e.message})}};
 return <div className="audits-workspace"><Toast toast={toast} onClose={()=>setToast(null)}/><section className="audit-browser panel"><div className="browser-top"><div className="search-box"><Search size={17}/><input id="audit-search" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search audit portfolio…"/></div><button className="icon-btn" onClick={load} title="Refresh"><RefreshCw size={17}/></button></div><div className="audit-list">{filtered.map(a=><button className={`audit-select ${selected?.id===a.id?'active':''}`} key={a.id} onClick={()=>choose(a)}><span className="audit-row-icon"><Shield size={18}/></span><span className="grow"><b>{a.project_name}</b><small>{a.workflows.length} workflow{a.workflows.length===1?'':'s'}</small></span><span className={`risk-dot ${(a.risk_level||'pending').toLowerCase()}`}/><ChevronRight size={16}/></button>)}{!filtered.length&&<div className="empty-mini"><FileJson2/><p>No audits match your search.</p></div>}</div><button className="primary-btn browser-new" onClick={()=>navigate('/new-audit')}>Create new audit</button></section>
 <section className="audit-detail">{selected?<><div className="audit-hero panel"><div><span className={`status-chip ${selected.status}`}>{selected.status.replace('_',' ')}</span><h2>{selected.project_name}</h2><p>{selected.description||'No project description provided.'}</p><div className="hero-meta"><span>Risk <b>{selected.risk_level||'Pending'}</b></span><span>Readiness <b>{selected.production_readiness||'Pending'}</b></span><span>Workflows <b>{selected.workflows.length}</b></span></div></div><ScoreOrb score={selected.overall_score||0} label="Overall score"/></div>
 <div className="audit-actions"><button className="soft-btn" onClick={rerun} disabled={busy||!selected.workflows.length}>{busy?<RefreshCw className="spin" size={17}/>:<Play size={17}/>} Run audit</button><button className="soft-btn" onClick={download}><ArrowDownToLine size={17}/> Download report</button><button className="danger-btn" onClick={remove} disabled={busy}><Trash2 size={17}/> Delete</button></div>
 <div className="audit-tabs"><button className={tab==='findings'?'active':''} onClick={()=>setTab('findings')}>Findings <span>{selected.findings.length}</span></button><button className={tab==='recommendations'?'active':''} onClick={()=>setTab('recommendations')}>Recommendations <span>{selected.recommendations.length}</span></button><button className={tab==='workflows'?'active':''} onClick={()=>setTab('workflows')}>Workflows <span>{selected.workflows.length}</span></button></div>
 <div className="audit-content panel">{tab==='findings'&&<div className="finding-grid">{selected.findings.map(f=><article className="finding-card" key={f.id}><div className="finding-top"><span className={`severity ${f.severity}`}>{f.severity}</span><span>{f.category}</span></div><h3>{f.title}</h3><p>{f.detail}</p><div className="evidence-box"><b>Evidence</b><span>{f.evidence||'No evidence text provided.'}</span></div><footer><AlertCircle size={15}/>{f.impact}</footer></article>)}{!selected.findings.length&&<Empty text="Run this audit to generate findings."/>}</div>}
 {tab==='recommendations'&&<div className="recommendation-list">{selected.recommendations.map(r=><article key={r.id}><span className={`priority ${r.priority.toLowerCase()}`}>{r.priority}</span><div><small>{r.category}</small><h3>{r.title}</h3><p>{r.action}</p><div className="recommendation-meta"><span><b>Why</b>{r.rationale}</span><span><b>Expected impact</b>{r.expected_impact}</span></div></div></article>)}{!selected.recommendations.length&&<Empty text="No recommendations stored yet."/>}</div>}
 {tab==='workflows'&&<div className="workflow-grid">{selected.workflows.map(w=><article key={w.id}><span className="feature-icon"><Workflow/></span><h3>{w.name}</h3><div className="workflow-metrics"><span><b>{w.node_count}</b>Nodes</span><span><b>{w.trigger_count}</b>Triggers</span><span><b>{w.ai_node_count}</b>AI nodes</span><span><b>{w.integration_count}</b>Integrations</span><span><b>{w.connection_count}</b>Connections</span></div></article>)}{!selected.workflows.length&&<Empty text="No workflow files uploaded."/>}</div>}</div></>:<div className="panel empty-large"><Sparkles/><h2>Your audit workspace is empty</h2><p>Create an audit and upload an n8n workflow JSON to begin.</p><button className="primary-btn" onClick={()=>navigate('/new-audit')}>Launch first audit</button></div>}</section></div>;
}
function Empty({text}){return <div className="empty-large"><Sparkles/><p>{text}</p></div>}
