import { useNavigate } from 'react-router-dom';
import { ArrowRight, CheckCircle2, FileJson2, Sparkles, ShieldCheck, ScanSearch, Workflow, Gauge } from 'lucide-react';
import hero from '../assets/hero-audit-orb.png';
import orbit from '../assets/workflow-orbit.png';

export default function Landing() {
  const navigate = useNavigate();
  return <div className="landing">
    <header className="landing-nav"><button className="brand landing-brand" onClick={()=>navigate('/')}><span className="brand-mark"><ShieldCheck size={22}/></span><span><b>Auditra</b><small>AI Workflow Intelligence</small></span></button><div className="landing-links"><button onClick={()=>document.getElementById('capabilities')?.scrollIntoView({behavior:'smooth'})}>Capabilities</button><button onClick={()=>document.getElementById('method')?.scrollIntoView({behavior:'smooth'})}>How it works</button><button className="soft-btn" onClick={()=>navigate('/dashboard')}>Open workspace</button></div></header>
    <section className="hero"><div className="hero-copy"><span className="pill"><Sparkles size={15}/> Structural rules + AI-assisted review</span><h1>Turn complex workflows into <em>clear audit decisions.</em></h1><p>Inspect n8n automation architecture, reliability, security, and AI governance — then convert the evidence into prioritized recommendations.</p><div className="hero-actions"><button className="primary-btn" onClick={()=>navigate('/new-audit')}>Start a new audit <ArrowRight size={18}/></button><button className="ghost-btn" onClick={()=>navigate('/audits')}>Explore existing audits</button></div><div className="trust-row"><span><CheckCircle2 size={16}/> Evidence-led</span><span><CheckCircle2 size={16}/> Local workflow upload</span><span><CheckCircle2 size={16}/> Production readiness scoring</span></div></div><div className="hero-visual"><div className="hero-halo"/><img src={hero} alt="3D shield and workflow assurance illustration"/><div className="floating-card fc-one"><ScanSearch size={19}/><span><b>Deep scan</b><small>Architecture + governance</small></span></div><div className="floating-card fc-two"><Gauge size={19}/><span><b>Readiness</b><small>Score every project</small></span></div></div></section>
    <section className="capabilities" id="capabilities"><article><span className="feature-icon"><Workflow/></span><h3>Workflow topology</h3><p>Read nodes, triggers, integrations, branches, and connections from uploaded n8n JSON.</p></article><article><span className="feature-icon"><ScanSearch/></span><h3>Risk evidence</h3><p>Surface reliability, security, architecture, and AI-governance findings with explicit evidence.</p></article><article><span className="feature-icon"><Sparkles/></span><h3>Prioritized action</h3><p>Pair deterministic checks with AI review to produce concrete recommendations and impact.</p></article></section>
    <section className="method" id="method"><div className="method-visual"><img src={orbit} alt="Workflow nodes connected in an audit orbit"/></div><div><p className="eyebrow">FROM JSON TO DECISION</p><h2>A calm review loop for complicated automations.</h2><div className="step-list"><div><b>01</b><span><strong>Create the audit</strong><small>Give the project a name and review context.</small></span></div><div><b>02</b><span><strong>Upload workflows</strong><small>Add one or more n8n JSON exports.</small></span></div><div><b>03</b><span><strong>Run & act</strong><small>Review score, findings, recommendations, and report.</small></span></div></div><button className="primary-btn" onClick={()=>navigate('/new-audit')}>Create audit <FileJson2 size={18}/></button></div></section>
    <footer className="landing-footer"><span>Auditra</span><small>AI Workflow Audit & Recommendation Interface</small></footer>
  </div>;
}
