import { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { Check, FileJson2, FolderPlus, LoaderCircle, PlayCircle, UploadCloud, X } from 'lucide-react';
import { api } from '../lib/api'; import Toast from '../components/Toast'; import orbit from '../assets/workflow-orbit.png';

export default function NewAudit(){
 const navigate=useNavigate(); const [name,setName]=useState(''); const [desc,setDesc]=useState(''); const [files,setFiles]=useState([]); const [running,setRunning]=useState(false); const [step,setStep]=useState(1); const [toast,setToast]=useState(null);
 const addFiles=(incoming)=>{const valid=[...incoming].filter(f=>f.name.toLowerCase().endsWith('.json'));if(valid.length!==incoming.length)setToast({type:'error',message:'Only n8n .json workflow exports are accepted.'});setFiles(prev=>[...prev,...valid.filter(f=>!prev.some(p=>p.name===f.name&&p.size===f.size))])};
 const launch=async()=>{if(!name.trim()){setToast({type:'error',message:'Project name is required.'});return}if(!files.length){setToast({type:'error',message:'Add at least one workflow JSON file.'});return}setRunning(true);try{setStep(2);let audit=await api.createAudit({project_name:name.trim(),description:desc.trim()});for(const file of files){audit=await api.uploadWorkflow(audit.id,file)}setStep(3);audit=await api.startAudit(audit.id);setStep(4);setToast({message:'Audit completed successfully.'});setTimeout(()=>navigate(`/audits?id=${audit.id}`),650)}catch(e){setToast({type:'error',message:e.message});setStep(1)}finally{setRunning(false)}};
 return <div className="new-audit-grid"><Toast toast={toast} onClose={()=>setToast(null)}/><section className="panel launch-form"><div className="form-heading"><span className="feature-icon"><FolderPlus/></span><div><p className="eyebrow">AUDIT SETUP</p><h2>Build the review context</h2><p>Everything here maps directly to your FastAPI audit flow.</p></div></div><label>Project name<input value={name} onChange={e=>setName(e.target.value)} placeholder="e.g. Customer Support Agent" disabled={running}/></label><label>Description<textarea value={desc} onChange={e=>setDesc(e.target.value)} placeholder="What does this automation do, and what matters in the review?" rows="4" disabled={running}/></label><div className="dropzone" onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();addFiles(e.dataTransfer.files)}}><UploadCloud size={30}/><h3>Drop n8n workflow JSON here</h3><p>or choose one or more files from your computer</p><label className="soft-btn file-picker">Choose workflow<input type="file" accept="application/json,.json" multiple hidden onChange={e=>addFiles(e.target.files)}/></label></div><div className="file-stack">{files.map((f,i)=><div key={`${f.name}-${i}`}><FileJson2 size={18}/><span className="grow"><b>{f.name}</b><small>{(f.size/1024).toFixed(1)} KB</small></span><button onClick={()=>setFiles(files.filter((_,x)=>x!==i))} disabled={running}><X size={16}/></button></div>)}</div><button className="primary-btn launch-btn" onClick={launch} disabled={running}>{running?<LoaderCircle className="spin" size={18}/>:<PlayCircle size={18}/>} {running?'Running audit…':'Create & run audit'}</button></section>
 <aside className="launch-side"><div className="launch-visual"><img src={orbit} alt="Audit workflow orbit illustration"/></div><div className="progress-card panel"><p className="eyebrow">LIVE FLOW</p>{[['Create audit',1],['Upload workflows',2],['Run audit engine',3],['Open results',4]].map(([label,n])=><div key={n} className={step>=n?'done':''}><span>{step>n?<Check size={14}/>:n}</span><p><b>{label}</b><small>{n===1?'POST /api/audits':n===2?'POST /workflow':n===3?'POST /start':'Audit workspace'}</small></p></div>)}</div></aside></div>;
}
